live_config_reload = true 

import = [
    "~/AppData/Roaming/alacritty/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[shell]
program = "Ubuntu"

[window]
dynamic_padding = true
decorations = "Full"
opacity = 0.8
startup_mode = "Maximized"
dynamic_title = true
decorations_theme_variant = "Dark"
option_as_alt = "both"

[font]
normal = { family = "MesloLGS NFM", style = "Regular" }
bold = { family = "MesloLGS NFM", style = "Bold" }
italic = { family = "MesloLGS NFM", style = "Italic" }
size = 12
offset = { x = 0, y = 0 }
builtin_box_drawing = true

[cursor] 
style = {shape = "Block", blinking = "On" }

[mouse] 
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true 

[[hints.enabled]]
command = "explorer.exe"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[keyboard]
bindings = [
{ key="v", mods="Control|Shift", action="Paste"},
{ key="Space", mods="Control", action="None"},
{ key="C", mods="Control|Shift", action="Copy"},
{ key="Q", mods="Alt", action="Quit" },
{ key="Space", mods="Control", chars="\u0000" },
{ key="N", mods="Control|Shift", action="CreateNewWindow"}
]
